// 場地卡定義（21 種）
export const FIELDS = [
  { id: 'complex_plane', name: '複數平面',
    desc: '允許 i；算式可為複數以模長作傷害；歐拉公式免代價。' },
  { id: 'non_euclidean', name: '非歐幾里得空間',
    desc: '畢氏定理失效；餘弦角 C 可 >180°；幾何公式 +15；每回合雙方各抽 1 技能。' },
  { id: 'finite_field', name: '有限體GF(p)',
    desc: '結果取模 p(進場宣告)；(0~p-1)×20 作傷害；除以 0 得 0；CRT 翻倍。' },
  { id: 'riemann_sphere', name: '黎曼球面',
    desc: '∞ 造成 50 傷害；除以 0 視為 ∞；lim 可趨近 ∞；洛必達必成。' },
  { id: 'hilbert_space', name: '希爾伯特空間',
    desc: '∑ 上限提至 100；⊗ +20；薛丁格免費；每回合可多打 1 張公式卡。' },
  { id: 'p_adic', name: 'p進數域',
    desc: '可被 5 整除傷害 ÷5；可被 3 整除 +40；對手 log 結果 ×0.5。' },
  { id: 'quaternion', name: '四元數空間',
    desc: '引入 j、k；乘法不交換可反轉取高傷；含 2+ 虛數單位 +25。' },
  { id: 'hyperbolic', name: '雙曲幾何',
    desc: 'sin/cos 改用 sinh/cosh(×1)；回合傷害 <50 額外扣自身 25HP。' },
  { id: 'projective', name: '射影幾何',
    desc: '除以 0 有效得 80 傷害；不可被莫比烏斯帶反轉；雙方傷害 +25。' },
  { id: 'modular', name: '模運算場地',
    desc: '結果取模 12；×20 作傷害；費馬小/CRT 各 +25；數字 0 等同 12。' },
  { id: 'topology', name: '拓撲空間',
    desc: '6 與 9 可互換；括號可重排；四色定理加倍；莫比烏斯帶持續 2 回合。' },
  { id: 'probability_space', name: '機率空間',
    desc: '每回合傷害後隨機 -15/不變/+15；貝氏必成；大數法則第 2 回合起可用。' },
  { id: 'fractal', name: '分形宇宙',
    desc: '本回合可計算兩次(第二次 ÷2)；費氏數列持續 5 回合；最大最小數字差為額外傷害。' },
  { id: 'entanglement', name: '量子糾纏場',
    desc: '雙方各糾纏 1 張手牌；同類型翻開觸發抽 2 張；防禦技能與防禦區效果失效。' },
  { id: 'matrix_space', name: '矩陣空間',
    desc: '結果可視為 2×2 行列式；特徵值增幅提升；克拉瑪搜索 3→4 張。' },
  { id: 'infinite_dim', name: '無限維空間',
    desc: '∑ 可宣告無限求和(收斂得級數和/發散扣 50HP)；泰勒每張 +5 疊加。' },
  { id: 'void', name: '虛空',
    desc: '數字 0 造成 50 傷害；傷害下限 1；哥德巴赫必觸發偶數加倍；無公式回合抽 1 張。' },
  { id: 'chaos_edge', name: '混沌邊緣',
    desc: '每回合傷害隨機 ±25；差距 >50 較大方抽 1 張；混沌理論免代價；不可被替換。' },
  { id: 'golden_ratio', name: '黃金比例空間',
    desc: 'φ 精確；傷害為費氏數 +10；費氏數列加速；含 φ 算式 +25。' },
  { id: 'hyperreal', name: '超實數域',
    desc: '取整操作取消；lim 可精確至 ε；含無窮大因子傷害改為 150。' },
  { id: 'trig_space', name: '三角空間',
    desc: '任意數字卡用三角函數時可宣告為標準角(每張限一次)；三角乘數提至 ×60。' },
];

export const FIELD_BY_ID = Object.fromEntries(FIELDS.map((f) => [f.id, f]));
export const FIELD_BY_NAME = Object.fromEntries(FIELDS.map((f) => [f.name, f.id]));
